language: java
jdk:
  - openjdk8
  - openjdk11
env:
  - phase="test" pl="" additionalprops=""
  - phase="verify" pl="-pl systests/qpid-systests-jms_1.1,systests/qpid-systests-jms_2.0,systests/qpid-systests-http-management" additionalprops="-DskipTests -DskipITs=false"
script: "mvn --fail-at-end ${phase} ${pl} ${additionalprops}"
