language: java
sudo: false
jdk:
  - oraclejdk8
env:
  - phase="test" pl="" additionalprops="-Dskip.systests=true"
  - phase="verify" pl="-pl systests/protocol-tests-amqp-1-0,systests/protocol-tests-amqp-0-8,systests/protocol-tests-amqp-0-10" additionalprops="-Dskip.unittests=true"
script: "mvn --fail-at-end --threads 2.0C ${phase} ${pl} ${additionalprops} -Dtest.overridden.properties=${TRAVIS_BUILD_DIR}/test-profiles/apache-ci.test.overridden.properties"
