language: java
sudo: false
jdk:
  - oraclejdk8
env:
  - phase="test" pl=""
  - phase="verify" pl="-pl systests/protocol-tests-amqp-1-0,systests/protocol-tests-amqp-0-8,systests/protocol-tests-amqp-0-10"
script: "mvn ${phase} ${pl} -Dtest.overridden.properties=${TRAVIS_BUILD_DIR}/test-profiles/apache-ci.test.overridden.properties"
